
invite = ["Albert Einstein", "Stephen Hawking", "Wilbur and Orville Wright","Lapu-Lapu","Ferdinand Magellan"]

for invitees in invite:
    print (f"I would like to invite ,{invitees} to dinner.")

print ("\nUnfortunately Mr.Lapu-Lapu won't be able to make it to the dinner tonight.\n")

invite = ["Albert Einstein", "Stephen Hawking", "Wilbur and Orville Wright","Andrés Bonifacio","Ferdinand Magellan"]

for invitees in invite:
    print (f"I would like to invite ,{invitees} to dinner.")
