
#Alien color green
print ("For the alien color Green:\n")
alien_color = 'green'
if alien_color == 'green':
    print ("You just earned 5 points.\n")

elif alien_color == "yellow":
    print ("You just earned 10 points.\n")
else: 
    print ("You just earned 15 points.\n")
    
#Alien color yellow
print ("For the alien color Yellow:\n")
alien_color = 'yellow'
if alien_color == 'green':
    print ("You just earned 5 points.\n")

elif alien_color == "yellow":
    print ("You just earned 10 points.\n")
else: 
    print("You just earned 15 points.\n")

#Alien color red
print("For the alien color Red:\n")
alien_color = 'red'
if alien_color == 'green':
    print("You just earned 5 points.\n")

elif alien_color == "yellow":
    print("You just earned 10 points.\n")
else: 
    print("You just earned 15 points.\n")
