
alien_color = 'green'
if alien_color == 'green':
    print ("You just earned 5 points for shooting the alien.")
else: 
    print ("You just earned 10 points.")

#This comment indicates that the code below is the "•Write one version of this program that runs the if block and another that runs the else block."

alien_color = 'red'
if alien_color == 'green':
    print ("You just earned 5 points for shooting the alien.")
else: 
    print ("You just earned 10 points.")
