
favorite_fruits = ["Apples","Grapes","Pineapples"]

for fruits in favorite_fruits:
    if fruits in ["Apples"]:
         print(f"You really like {fruits}!\n")


for fruits in favorite_fruits:
    if fruits in ["Grapes"]:
         print(f"You really like {fruits}!\n")


for fruits in favorite_fruits:
    if fruits in ["Pineapples"]:
         print(f"You really like {fruits}!\n")


for fruits in favorite_fruits:
    if fruits in ["Oranges"]:
         print(f"You really like {fruits}!\n")


for fruits in favorite_fruits:
    if fruits in ["Cherry"]:
         print(f"You really like {fruits}!\n")
