
glossary = {'Variables':'A variable is a reserved memory location to store values.',
            'Values':'It is either a letter or number that works with the program.',
            'Comments':'It enhances the readability of the code and help the programmers to understand the code very carefully.',
            'Print':'Is a function that prints specified message to the screen, or other standard output device.',
            'Lists':'Is a collection of things, enclosed in [ ] and separated by commas.'}

print (f"Variables:\n{glossary['Variables']}\n")
print (f"Values:\n{glossary['Values']}\n")
print (f"Comments:\n{glossary['Comments']}\n")
print (f"Print:\n{glossary['Print']}\n")
print (f"Lists:\n{glossary['Lists']}\n")
